- name: Install php
  sudo: yes
  yum: name={{ item }} state=present
  with_items:
    - php
    - php-cli
    - php-common
    - php-devel
    - php-fpm
    - php-json
    - php-mbstring
    - php-mcrypt
    - php-mysql
    - php-pdo
    - php-process
    - php-xml